name: Test, build and release wheels

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci-${{ matrix.os }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: python -m pip install .[tests,ci]

      - name: flake8 lint
        run: flake8

      - name: black formatting Check
        run: black --check .

      - name: pytest and coverage
        run: coverage run -m pytest && coverage report -i --fail-under=90

      - name: build wheels
        run: python -m pip wheel -w ./wheelhouse/ .

      - uses: actions/upload-artifact@v3
        with:
          name: ci-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./wheelhouse/*.whl
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: ci
    steps:
      - name: take artifact
        run: echo don't know how to do it

      - name: create a github release from tag
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: ./wheelhouse/*.whl
